export const FEED_FETCH_USER_LOCATION = 'FEED_FETCH_USER_LOCATION';
export const FEED_FETCH_USER_LOCATION_CANCEL = 'FEED_FETCH_USER_LOCATION_CANCEL';
export const FEED_FETCH_USER_LOCATION_FINISHED = 'FEED_FETCH_USER_LOCATION_FINISHED';

export const FEED_FETCH_EVENTS_BY_LOCATION = 'FEED_FETCH_EVENTS_BY_LOCATION';
export const FEED_FETCH_EVENTS_BY_LOCATION_CANCEL = 'FEED_FETCH_EVENTS_BY_LOCATION_CANCEL';
export const FEED_FETCH_EVENTS_BY_LOCATION_FINISHED = 'FEED_FETCH_EVENTS_BY_LOCATION_FINISHED';

