export const USER_UPDATE_USER_DATA = 'USER_UPDATE_USER_DATA';
export const USER_UPDATE_USER_DATA_SUCCESS = 'USER_UPDATE_USER_DATA_SUCCESS';
export const USER_UPDATE_USER_DATA_ERROR = 'USER_UPDATE_USER_DATA_ERROR';
