export const SIDEBAR_TOGGLE_VISIBILITY = 'SIDEBAR_TOGGLE_VISIBILITY';
export const SIDEBAR_SET_VISIBILITY = 'SIDEBAR_SET_VISIBILITY';
export const SIDEBAR_REMOVE_VISIBILITY = 'SIDEBAR_REMOVE_VISIBILITY';
export const BOTTOMBAR_TOGGLE_VISIBILITY = 'BOTTOMBAR_TOGGLE_VISIBILITY';
export const BOTTTOMBAR_SET_VISIBILITY = 'BOTTTOMBAR_SET_VISIBILITY';
export const BOTTTOMBAR_REMOVE_VISIBILITY = 'BOTTTOMBAR_REMOVE_VISIBILITY';
