export const SIDEBAR_TOGGLE_VISIBILITY = 'SIDEBAR_TOGGLE_VISIBILITY';
export const SIDEBAR_SET_VISIBILITY = 'SIDEBAR_SET_VISIBILITY';
export const SIDEBAR_REMOVE_VISIBILITY = 'SIDEBAR_REMOVE_VISIBILITY';
