export const COMMENTS_FETCH_THREAD = 'COMMENTS_FETCH_THREAD';
export const COMMENTS_FETCH_THREAD_SUCCESS = 'COMMENTS_FETCH_THREAD_SUCCESS';
export const COMMENTS_FETCH_THREAD_ERROR = 'COMMENTS_FETCH_THREAD_ERROR';
export const COMMENTS_FETCH_THREAD_CANCEL = 'COMMENTS_FETCH_THREAD_CANCEL';

export const COMMENTS_POST_TO_THREAD = 'COMMENTS_POST_TO_THREAD';
export const COMMENTS_POST_TO_THREAD_SUCCESS = 'COMMENTS_POST_TO_THREAD_SUCCESS';
export const COMMENTS_POST_TO_THREAD_ERROR = 'COMMENTS_POST_TO_THREAD_ERROR';
export const COMMENTS_POST_TO_THREAD_CANCEL = 'COMMENTS_POST_TO_THREAD_CANCEL';

