export const AUTH_LOGIN_SUBMIT_EMAIL_PASSWORD = 'AUTH_LOGIN_SUBMIT_EMAIL_PASSWORD';
export const AUTH_LOGIN_SUCCESS_EMAIL_PASSWORD = 'AUTH_LOGIN_SUCCESS_EMAIL_PASSWORD';
export const AUTH_LOGIN_ERROR_EMAIL_PASSWORD = 'AUTH_LOGIN_ERROR_EMAIL_PASSWORD';

export const AUTH_SIGNUP_EMAIL_PASSWORD = 'AUTH_SIGNUP_EMAIL_PASSWORD';
export const AUTH_SIGNUP_EMAIL_PASSWORD_SUCCESS = 'AUTH_SIGNUP_EMAIL_PASSWORD_SUCCESS';
export const AUTH_SIGNUP_EMAIL_PASSWORD_ERROR = 'AUTH_SIGNUP_EMAIL_PASSWORD_ERROR';

export const AUTH_LOGOUT_SUBMIT = 'AUTH_LOGOUT_SUBMIT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

export const AUTH_CHECK_USER_STATUS = 'AUTH_CHECK_USER_STATUS';
export const AUTH_CHECK_USER_STATUS_FINISHED = 'AUTH_CHECK_USER_STATUS_FINISHED';

export const AUTH_UPDATE_USER_DATA = 'AUTH_UPDATE_USER_DATA';

export const AUTH_SEND_VERIFICATION_EMAIL = 'AUTH_SEND_VERIFICATION_EMAIL';
export const AUTH_SEND_VERIFICATION_EMAIL_SUCCESS = 'AUTH_SEND_VERIFICATION_EMAIL_SUCCESS';
export const AUTH_SEND_VERIFICATION_EMAIL_ERROR = 'AUTH_SEND_VERIFICATION_EMAIL_ERROR';

export const AUTH_VERIFY_EMAIL_LINK = 'AUTH_VERIFY_EMAIL_LINK';
export const AUTH_VERIFY_EMAIL_LINK_SUCCESS = 'AUTH_VERIFY_EMAIL_LINK_SUCCESS';
export const AUTH_VERIFY_EMAIL_LINK_ERROR = 'AUTH_VERIFY_EMAIL_LINK_ERROR';

export const AUTH_OAUTH_SIGNIN = 'AUTH_OAUTH_SIGNIN';
export const AUTH_OAUTH_SIGNIN_SUCCESS = 'AUTH_OAUTH_SIGNIN_SUCCESS';
export const AUTH_OAUTH_SIGNIN_ERROR = 'AUTH_OAUTH_SIGNIN_ERROR';
