export const GEOLOCATOR_LOCATION_FETCH = 'GEOLOCATOR_LOCATION_FETCH';
export const GEOLOCATOR_LOCATION_GET_PERMISSION = 'GEOLOCATOR_LOCATION_GET_PERMISSION';
export const GEOLOCATOR_LOCATION_DENIED = 'GEOLOCATOR_LOCATION_DENIED';
export const GEOLOCATOR_LOCATION_FAILED = 'GEOLOCATOR_LOCATION_FAILED';
export const GEOLOCATOR_LOCATION_SUCCESS = 'GEOLOCATOR_LOCATION_SUCCESS';
export const GEOLOCATOR_MODAL_OPEN = 'GEOLOCATOR_MODAL_OPEN';
export const GEOLOCATOR_MODAL_CLOSE = 'GEOLOCATOR_MODAL_CLOSE';

